#/bin/bash

# ./constrained_clustering MincutGlobalClusterRepeat --edgelist ./examples/connected_components.tsv --algorithm leiden-cpm --resolution 0.01 --num-processors 1 --output-file ./output_clusters.tsv --log-file .//output.log --log-level 2
# ./constrained_clustering MincutGlobalClusterRepeat --edgelist ./examples/mincut_then_leiden.tsv --algorithm leiden-cpm --resolution 0.01 --num-processors 1 --output-file ./output_clusters.tsv --log-file .//output.log --log-level 2
# ./constrained_clustering MincutGlobalClusterRepeat --edgelist ./examples/mincut_then_leiden.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 5 --output-file ./output_clusters.tsv --log-file .//output.log --log-level 2
# ./constrained_clustering MincutGlobalClusterRepeat --edgelist ./examples/mincut_then_leiden.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 5 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 1
# ./constrained_clustering MincutGlobalClusterRepeat --edgelist ./examples/mincut_then_leiden.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 5 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 1 #--start-with-clustering
# mpirun -n 2 constrained_clustering CM --edgelist ./examples/cm_test.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 5 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2
# ./constrained_clustering CM --edgelist ./examples/cm_test.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2
# ./constrained_clustering CM --edgelist ./examples/cm_test.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2 --start-with-clustering
# mpirun -n 2 constrained_clustering CM --edgelist ./examples/connected_components.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2 # --start-with-clustering
# ./constrained_clustering CM --edgelist ./examples/connected_components.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2
# ./constrained_clustering CM --edgelist ./examples/connected_components_trivial_mincuts.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2
# mpirun -n 2 constrained_clustering CM --edgelist ./examples/connected_components_trivial_mincuts.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2
# mpirun -n 2 constrained_clustering CM --edgelist ./examples/mincut_then_leiden.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2
# mpirun -n 2 constrained_clustering CM --edgelist ./examples/mincut_then_leiden.tsv  --existing-clustering ./examples/mtl_clusters.tsv --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters.tsv --log-file ./output.log --log-level 2
# mpirun -n 1 constrained_clustering CM --edgelist ./examples/test_network_simple_1.tsv --existing-clustering ./examples/test_clustering_simple_1_filtered.tsv  --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_clusters_network_simple.tsv --log-file ./output_network_simple.log --log-level 2
# mpirun -n 4 constrained_clustering CM --edgelist ./examples/test_network.tsv --existing-clustering ./examples/test_clustering_filtered.tsv  --algorithm leiden-cpm --resolution 0.2 --num-processors 1 --output-file ./output_network_clusters.tsv --log-file ./output_network_clusters.log --log-level 2
